# Generated by Django 5.2.11 on 2026-02-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.TextField(blank=True, help_text='Pipe-separated image URLs', null=True),
        ),
    ]
