# Generated by Django 5.2.11 on 2026-02-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode from JSON', max_length=100, null=True),
        ),
    ]
