# Generated by Django 5.2.11 on 2026-02-06 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
