# Generated by Django 5.2.11 on 2026-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(decimal_places=3, default=600.0, max_digits=12),
        ),
    ]
