# Generated by Django 5.2.11 on 2026-02-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_preferences',
        ),
    ]
